modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "nethervinery"
version = "${version}"
displayName = "Nether Vinery"
authors = "satisfyu"
description = '''
Welcome to Nether Vinery! New grapes, new decor - all in the style of the Nether.
'''
#logoFile = ""

[[dependencies.nethervinery]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nethervinery]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nethervinery]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.77,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.nethervinery]]
modId = "vinery"
mandatory = true
versionRange = "[1.3.12,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.nethervinery]]
modId = "doapi"
mandatory = true
versionRange = "[1.1.0,)"
ordering = "AFTER"
side = "BOTH"